### ISSUE TITLE
setup_perf_event fails with ENODEV (`perf` works)

### ISSUE THREAD

**Issue by shaver** [javierhonduco/rbperf#49]
Hi there,

When I run the suggested steps in `tests/programs/Dockerfile.server`, `rbperf` errors out with

```
pid: 38686
libruby: /usr/local/lib/libruby.so.3.0.0 @ 0x7f54251d7000
ruby main thread address: 0x7f5425598138
process base address: 0x55b26e96f000
ruby version: "3.0.0"

Error: setup_perf_event failed with errno No such device
```

According to the `perf_event_open(2)` docs, this indicates that my CPU is missing a feature, but standard Linux `perf` can sample from that `ruby` process without problem.

My cpuinfo is attached in case it's helpful (AMD 5800X3D): [cpuinfo.txt](https://github.com/javierhonduco/rbperf/files/10094741/cpuinfo.txt)

I'm running kernel `Linux CRAGNOR 6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000 x86_64 GNU/Linux`

I'm not sure if it's a configuration issue (in which case I'll submit a PR for `README.md`) or some limitation of the way that `rbperf` is configuring the perf events.

**Comment by shaver** [comment]
I finally thought of stracing it, and `perf_event_open` works correctly a number of times, but then fails trying to do so for CPU #16.  I have 16 logical processors (0-15), but `/sys/devices/system/cpu/possible` which underlies `num_possible_cpus` reports `0-31`. Should `setup_perf_event` or `start` handle this more gracefully, or do I have a system misconfiguration here?

[strace.txt](https://github.com/javierhonduco/rbperf/files/10096999/strace.txt)

**Comment by shaver** [comment]
I have SMT on; 5800X3D is 8C/16T. I don't know where the possible of 0-31 comes from, but it survives disabling hyperthreading as well:

```
[shaver@CRAGNOR ~]$ cat /sys/devices/system/cpu/smt/active 
1
[shaver@CRAGNOR ~]$ cat /sys/devices/system/cpu/possible
0-31
[shaver@CRAGNOR ~]$ cat /sys/devices/system/cpu/online
0-15
[shaver@CRAGNOR ~]$ echo off | sudo tee /sys/devices/system/cpu/smt/control
off
[shaver@CRAGNOR ~]$ cat /sys/devices/system/cpu/smt/active 
0
[shaver@CRAGNOR ~]$ cat /sys/devices/system/cpu/possible
0-31
[shaver@CRAGNOR ~]$ cat /sys/devices/system/cpu/online
0-7
```

**Comment by javierhonduco** [comment]
Found [this SO post](https://unix.stackexchange.com/questions/609555/how-does-linux-detect-number-of-possible-cpus), could be related to what you are seeing

**Comment by javierhonduco** [comment]
(closing as your PR fixes the issue)
